# Generated by Django 5.0.6 on 2026-08-07 10:17

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(db_index=True, max_length=10, unique=True, validators=[apps.core.validators.validate_mobile_number])),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6, validators=[apps.core.validators.validate_pincode])),
                ('loan_type', models.CharField(choices=[('HOME_LOAN', 'Home Loan'), ('LAP', 'Loan Against Property')], max_length=20)),
                ('employment_type', models.CharField(choices=[('SALARIED', 'Salaried'), ('SELF_EMPLOYED', 'Self Employed')], max_length=20)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_amount_required', models.DecimalField(decimal_places=2, max_digits=14)),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('credit_score', models.PositiveIntegerField(blank=True, null=True)),
                ('bre_status', models.CharField(choices=[('PENDING', 'Pending'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bre_status'], name='leads_lead_bre_sta_28c586_idx'), models.Index(fields=['loan_type'], name='leads_lead_loan_ty_914061_idx')],
            },
        ),
    ]
