# Generated by Django 5.0.6 on 2026-08-07 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('field_name', models.CharField(choices=[('age', 'Age'), ('monthly_income', 'Monthly Income'), ('credit_score', 'Credit Score'), ('loan_amount', 'Loan Amount Required'), ('property_value', 'Property Value'), ('employment_type', 'Employment Type'), ('loan_type', 'Loan Type')], max_length=30)),
                ('operator', models.CharField(choices=[('>=', 'Greater than or equal to'), ('<=', 'Less than or equal to'), ('>', 'Greater than'), ('<', 'Less than'), ('==', 'Equal to'), ('!=', 'Not equal to')], max_length=5)),
                ('comparison_type', models.CharField(choices=[('ABSOLUTE', 'Absolute value'), ('PERCENT_OF_FIELD', 'Percentage of another field')], default='ABSOLUTE', max_length=20)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('percent_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reference_field', models.CharField(blank=True, choices=[('age', 'Age'), ('monthly_income', 'Monthly Income'), ('credit_score', 'Credit Score'), ('loan_amount', 'Loan Amount Required'), ('property_value', 'Property Value'), ('employment_type', 'Employment Type'), ('loan_type', 'Loan Type')], max_length=30, null=True)),
                ('rejection_reason', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower runs first.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleEvaluationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name_snapshot', models.CharField(max_length=30)),
                ('operator_snapshot', models.CharField(max_length=5)),
                ('resolved_subject_value', models.CharField(max_length=50)),
                ('resolved_threshold_value', models.CharField(max_length=50)),
                ('passed', models.BooleanField()),
                ('rejection_reason_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_evaluations', to='leads.lead')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_logs', to='bre.businessrule')),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
