--
-- PostgreSQL database dump
--

\restrict fMD8Y1oOqGUyX5XlQy17Mm0VGCe68eyOguFJDZu1kT6OgvuKXwOV0M56W0aPr4m

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_adminuser; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_adminuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL,
    email character varying(254) NOT NULL
);


--
-- Name: accounts_adminuser_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_adminuser_groups (
    id bigint NOT NULL,
    adminuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: accounts_adminuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_adminuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_adminuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_adminuser_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_adminuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_adminuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_adminuser_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_adminuser_user_permissions (
    id bigint NOT NULL,
    adminuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: accounts_adminuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_adminuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_adminuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bre_businessrule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bre_businessrule (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(150) NOT NULL,
    field_name character varying(30) NOT NULL,
    operator character varying(5) NOT NULL,
    comparison_type character varying(20) NOT NULL,
    value character varying(50),
    percent_value numeric(5,2),
    reference_field character varying(30),
    rejection_reason character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    priority integer NOT NULL,
    created_by_id bigint,
    CONSTRAINT bre_businessrule_priority_check CHECK ((priority >= 0))
);


--
-- Name: bre_businessrule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bre_businessrule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bre_businessrule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bre_ruleevaluationlog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bre_ruleevaluationlog (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    field_name_snapshot character varying(30) NOT NULL,
    operator_snapshot character varying(5) NOT NULL,
    resolved_subject_value character varying(50) NOT NULL,
    resolved_threshold_value character varying(50) NOT NULL,
    passed boolean NOT NULL,
    rejection_reason_snapshot character varying(255),
    evaluated_at timestamp with time zone NOT NULL,
    lead_id bigint NOT NULL,
    rule_id bigint
);


--
-- Name: bre_ruleevaluationlog_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bre_ruleevaluationlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bre_ruleevaluationlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: credit_score_creditscorerecord; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit_score_creditscorerecord (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    provider character varying(20) NOT NULL,
    score integer,
    status character varying(10) NOT NULL,
    raw_response jsonb,
    error_message text,
    fetched_at timestamp with time zone NOT NULL,
    lead_id bigint NOT NULL,
    CONSTRAINT credit_score_creditscorerecord_score_check CHECK ((score >= 0))
);


--
-- Name: credit_score_creditscorerecord_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credit_score_creditscorerecord ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.credit_score_creditscorerecord_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: leads_lead; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.leads_lead (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    full_name character varying(150) NOT NULL,
    mobile_number character varying(10) NOT NULL,
    email character varying(254) NOT NULL,
    date_of_birth date NOT NULL,
    city character varying(100) NOT NULL,
    pincode character varying(6) NOT NULL,
    loan_type character varying(20) NOT NULL,
    employment_type character varying(20) NOT NULL,
    monthly_income numeric(12,2) NOT NULL,
    loan_amount_required numeric(14,2) NOT NULL,
    property_value numeric(14,2) NOT NULL,
    consent_given boolean NOT NULL,
    consent_timestamp timestamp with time zone,
    credit_score integer,
    bre_status character varying(20) NOT NULL,
    CONSTRAINT leads_lead_credit_score_check CHECK ((credit_score >= 0))
);


--
-- Name: leads_lead_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.leads_lead ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leads_lead_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) NOT NULL
);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_adminuser; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.accounts_adminuser (id, password, last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, role, email) FROM stdin;
1	pbkdf2_sha256$720000$RezpTk8mCaTauwp2vqQSMg$oDhdHPB1dA3Tnp+3+X+2H2d4aJ/51KxUvVNzxLHeLns=	\N	t	admin			t	t	2026-08-07 15:49:55.134754+05:30	SUPER_ADMIN	admin@loanmanagement.local
\.


--
-- Data for Name: accounts_adminuser_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.accounts_adminuser_groups (id, adminuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_adminuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.accounts_adminuser_user_permissions (id, adminuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add blacklisted token	6	add_blacklistedtoken
22	Can change blacklisted token	6	change_blacklistedtoken
23	Can delete blacklisted token	6	delete_blacklistedtoken
24	Can view blacklisted token	6	view_blacklistedtoken
25	Can add outstanding token	7	add_outstandingtoken
26	Can change outstanding token	7	change_outstandingtoken
27	Can delete outstanding token	7	delete_outstandingtoken
28	Can view outstanding token	7	view_outstandingtoken
29	Can add user	8	add_adminuser
30	Can change user	8	change_adminuser
31	Can delete user	8	delete_adminuser
32	Can view user	8	view_adminuser
33	Can add credit score record	9	add_creditscorerecord
34	Can change credit score record	9	change_creditscorerecord
35	Can delete credit score record	9	delete_creditscorerecord
36	Can view credit score record	9	view_creditscorerecord
37	Can add business rule	10	add_businessrule
38	Can change business rule	10	change_businessrule
39	Can delete business rule	10	delete_businessrule
40	Can view business rule	10	view_businessrule
41	Can add rule evaluation log	11	add_ruleevaluationlog
42	Can change rule evaluation log	11	change_ruleevaluationlog
43	Can delete rule evaluation log	11	delete_ruleevaluationlog
44	Can view rule evaluation log	11	view_ruleevaluationlog
45	Can add lead	12	add_lead
46	Can change lead	12	change_lead
47	Can delete lead	12	delete_lead
48	Can view lead	12	view_lead
\.


--
-- Data for Name: bre_businessrule; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.bre_businessrule (id, created_at, updated_at, name, field_name, operator, comparison_type, value, percent_value, reference_field, rejection_reason, is_active, priority, created_by_id) FROM stdin;
1	2026-08-07 15:49:39.765274+05:30	2026-08-07 15:49:39.765274+05:30	Minimum Age	age	>=	ABSOLUTE	21	\N	\N	Applicant below minimum age requirement	t	10	\N
2	2026-08-07 15:49:39.78507+05:30	2026-08-07 15:49:39.78507+05:30	Maximum Age	age	<=	ABSOLUTE	60	\N	\N	Applicant above maximum age limit	t	20	\N
3	2026-08-07 15:49:39.792671+05:30	2026-08-07 15:49:39.792671+05:30	Minimum Monthly Income	monthly_income	>=	ABSOLUTE	30000	\N	\N	Monthly Income below eligibility criteria	t	30	\N
5	2026-08-07 15:49:39.812281+05:30	2026-08-07 15:49:39.812281+05:30	Loan Amount vs Property Value	loan_amount	<=	PERCENT_OF_FIELD	\N	80.00	property_value	Loan Amount exceeds eligible limit	t	50	\N
4	2026-08-07 15:49:39.800245+05:30	2026-08-07 15:53:20.089893+05:30	Minimum Credit Score	credit_score	>=	ABSOLUTE	700	\N	\N	Credit Score below minimum requirement	t	40	\N
\.


--
-- Data for Name: bre_ruleevaluationlog; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.bre_ruleevaluationlog (id, created_at, updated_at, field_name_snapshot, operator_snapshot, resolved_subject_value, resolved_threshold_value, passed, rejection_reason_snapshot, evaluated_at, lead_id, rule_id) FROM stdin;
1	2026-08-07 15:51:19.433527+05:30	2026-08-07 15:51:19.433527+05:30	age	>=	36	21	t	\N	2026-08-07 15:51:19.433527+05:30	1	1
2	2026-08-07 15:51:19.434542+05:30	2026-08-07 15:51:19.434542+05:30	age	<=	36	60	t	\N	2026-08-07 15:51:19.434542+05:30	1	2
3	2026-08-07 15:51:19.434542+05:30	2026-08-07 15:51:19.434542+05:30	monthly_income	>=	55000.00	30000	t	\N	2026-08-07 15:51:19.434542+05:30	1	3
4	2026-08-07 15:51:19.434542+05:30	2026-08-07 15:51:19.434542+05:30	credit_score	>=	608	700	f	Credit Score below minimum requirement	2026-08-07 15:51:19.434542+05:30	1	4
5	2026-08-07 15:51:19.434542+05:30	2026-08-07 15:51:19.434542+05:30	loan_amount	<=	2000000.00	2400000.0000	t	\N	2026-08-07 15:51:19.434542+05:30	1	5
6	2026-08-07 15:52:40.101718+05:30	2026-08-07 15:52:40.101718+05:30	age	>=	38	21	t	\N	2026-08-07 15:52:40.101718+05:30	2	1
7	2026-08-07 15:52:40.101718+05:30	2026-08-07 15:52:40.101718+05:30	age	<=	38	60	t	\N	2026-08-07 15:52:40.101718+05:30	2	2
8	2026-08-07 15:52:40.101718+05:30	2026-08-07 15:52:40.101718+05:30	monthly_income	>=	80000.00	30000	t	\N	2026-08-07 15:52:40.101718+05:30	2	3
9	2026-08-07 15:52:40.101718+05:30	2026-08-07 15:52:40.101718+05:30	credit_score	>=	673	700	f	Credit Score below minimum requirement	2026-08-07 15:52:40.101718+05:30	2	4
10	2026-08-07 15:52:40.101718+05:30	2026-08-07 15:52:40.101718+05:30	loan_amount	<=	1500000.00	2400000.0000	t	\N	2026-08-07 15:52:40.101718+05:30	2	5
11	2026-08-07 15:53:01.193127+05:30	2026-08-07 15:53:01.193127+05:30	age	>=	41	21	t	\N	2026-08-07 15:53:01.193127+05:30	3	1
12	2026-08-07 15:53:01.193127+05:30	2026-08-07 15:53:01.193127+05:30	age	<=	41	60	t	\N	2026-08-07 15:53:01.193127+05:30	3	2
13	2026-08-07 15:53:01.193127+05:30	2026-08-07 15:53:01.193127+05:30	monthly_income	>=	90000.00	30000	t	\N	2026-08-07 15:53:01.193127+05:30	3	3
14	2026-08-07 15:53:01.193127+05:30	2026-08-07 15:53:01.193127+05:30	credit_score	>=	727	700	t	\N	2026-08-07 15:53:01.193127+05:30	3	4
15	2026-08-07 15:53:01.193127+05:30	2026-08-07 15:53:01.193127+05:30	loan_amount	<=	2000000.00	2400000.0000	t	\N	2026-08-07 15:53:01.194485+05:30	3	5
16	2026-08-07 15:53:11.090878+05:30	2026-08-07 15:53:11.090878+05:30	age	>=	34	21	t	\N	2026-08-07 15:53:11.090878+05:30	4	1
17	2026-08-07 15:53:11.090878+05:30	2026-08-07 15:53:11.090878+05:30	age	<=	34	60	t	\N	2026-08-07 15:53:11.090878+05:30	4	2
18	2026-08-07 15:53:11.090878+05:30	2026-08-07 15:53:11.090878+05:30	monthly_income	>=	60000.00	30000	t	\N	2026-08-07 15:53:11.090878+05:30	4	3
19	2026-08-07 15:53:11.090878+05:30	2026-08-07 15:53:11.090878+05:30	credit_score	>=	327	600	f	Credit Score below minimum requirement	2026-08-07 15:53:11.090878+05:30	4	4
20	2026-08-07 15:53:11.090878+05:30	2026-08-07 15:53:11.090878+05:30	loan_amount	<=	1000000.00	1600000.0000	t	\N	2026-08-07 15:53:11.090878+05:30	4	5
21	2026-08-07 16:46:23.01735+05:30	2026-08-07 16:46:23.01735+05:30	age	>=	35	21	t	\N	2026-08-07 16:46:23.01735+05:30	5	1
22	2026-08-07 16:46:23.01735+05:30	2026-08-07 16:46:23.01735+05:30	age	<=	35	60	t	\N	2026-08-07 16:46:23.01735+05:30	5	2
23	2026-08-07 16:46:23.01735+05:30	2026-08-07 16:46:23.01735+05:30	monthly_income	>=	70000.00	30000	t	\N	2026-08-07 16:46:23.01735+05:30	5	3
24	2026-08-07 16:46:23.01735+05:30	2026-08-07 16:46:23.01735+05:30	credit_score	>=	725	700	t	\N	2026-08-07 16:46:23.01735+05:30	5	4
25	2026-08-07 16:46:23.01735+05:30	2026-08-07 16:46:23.01735+05:30	loan_amount	<=	1000000.00	2000000.0000	t	\N	2026-08-07 16:46:23.01735+05:30	5	5
26	2026-08-07 21:14:10.435647+05:30	2026-08-07 21:14:10.435647+05:30	age	>=	34	21	t	\N	2026-08-07 21:14:10.435647+05:30	6	1
27	2026-08-07 21:14:10.437662+05:30	2026-08-07 21:14:10.437662+05:30	age	<=	34	60	t	\N	2026-08-07 21:14:10.437662+05:30	6	2
28	2026-08-07 21:14:10.437662+05:30	2026-08-07 21:14:10.437662+05:30	monthly_income	>=	60000.00	30000	t	\N	2026-08-07 21:14:10.437662+05:30	6	3
29	2026-08-07 21:14:10.437662+05:30	2026-08-07 21:14:10.437662+05:30	credit_score	>=	831	700	t	\N	2026-08-07 21:14:10.437662+05:30	6	4
30	2026-08-07 21:14:10.437662+05:30	2026-08-07 21:14:10.437662+05:30	loan_amount	<=	1500000.00	2400000.0000	t	\N	2026-08-07 21:14:10.437662+05:30	6	5
31	2026-08-07 21:14:23.842743+05:30	2026-08-07 21:14:23.842743+05:30	age	>=	34	21	t	\N	2026-08-07 21:14:23.842743+05:30	7	1
32	2026-08-07 21:14:23.842743+05:30	2026-08-07 21:14:23.842743+05:30	age	<=	34	60	t	\N	2026-08-07 21:14:23.842743+05:30	7	2
33	2026-08-07 21:14:23.842743+05:30	2026-08-07 21:14:23.842743+05:30	monthly_income	>=	60000.00	30000	t	\N	2026-08-07 21:14:23.842743+05:30	7	3
34	2026-08-07 21:14:23.842743+05:30	2026-08-07 21:14:23.842743+05:30	credit_score	>=	656	700	f	Credit Score below minimum requirement	2026-08-07 21:14:23.842743+05:30	7	4
35	2026-08-07 21:14:23.842743+05:30	2026-08-07 21:14:23.842743+05:30	loan_amount	<=	1500000.00	2400000.0000	t	\N	2026-08-07 21:14:23.842743+05:30	7	5
36	2026-08-07 21:14:30.218894+05:30	2026-08-07 21:14:30.218894+05:30	age	>=	34	21	t	\N	2026-08-07 21:14:30.218894+05:30	8	1
37	2026-08-07 21:14:30.218894+05:30	2026-08-07 21:14:30.218894+05:30	age	<=	34	60	t	\N	2026-08-07 21:14:30.218894+05:30	8	2
38	2026-08-07 21:14:30.218894+05:30	2026-08-07 21:14:30.218894+05:30	monthly_income	>=	60000.00	30000	t	\N	2026-08-07 21:14:30.218894+05:30	8	3
39	2026-08-07 21:14:30.218894+05:30	2026-08-07 21:14:30.218894+05:30	credit_score	>=	865	700	t	\N	2026-08-07 21:14:30.218894+05:30	8	4
40	2026-08-07 21:14:30.218894+05:30	2026-08-07 21:14:30.218894+05:30	loan_amount	<=	1500000.00	2400000.0000	t	\N	2026-08-07 21:14:30.218894+05:30	8	5
\.


--
-- Data for Name: credit_score_creditscorerecord; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.credit_score_creditscorerecord (id, created_at, updated_at, provider, score, status, raw_response, error_message, fetched_at, lead_id) FROM stdin;
1	2026-08-07 15:51:19.408889+05:30	2026-08-07 15:51:19.408889+05:30	MOCK	608	SUCCESS	{"score": 608, "source": "mock", "mobile_number": "9876543210"}	\N	2026-08-07 15:51:19.408889+05:30	1
2	2026-08-07 15:52:40.081207+05:30	2026-08-07 15:52:40.081207+05:30	MOCK	673	SUCCESS	{"score": 673, "source": "mock", "mobile_number": "9123456780"}	\N	2026-08-07 15:52:40.081207+05:30	2
3	2026-08-07 15:53:01.166747+05:30	2026-08-07 15:53:01.166747+05:30	MOCK	727	SUCCESS	{"score": 727, "source": "mock", "mobile_number": "9000000007"}	\N	2026-08-07 15:53:01.166747+05:30	3
4	2026-08-07 15:53:11.07275+05:30	2026-08-07 15:53:11.07275+05:30	MOCK	327	SUCCESS	{"score": 327, "source": "mock", "mobile_number": "9876500001"}	\N	2026-08-07 15:53:11.07275+05:30	4
5	2026-08-07 16:46:22.996207+05:30	2026-08-07 16:46:22.996207+05:30	MOCK	725	SUCCESS	{"score": 725, "source": "mock", "mobile_number": "9988776655"}	\N	2026-08-07 16:46:22.996207+05:30	5
6	2026-08-07 21:14:10.42128+05:30	2026-08-07 21:14:10.42128+05:30	MOCK	831	SUCCESS	{"score": 831, "source": "mock", "mobile_number": "9800000000"}	\N	2026-08-07 21:14:10.42128+05:30	6
7	2026-08-07 21:14:23.823426+05:30	2026-08-07 21:14:23.823426+05:30	MOCK	656	SUCCESS	{"score": 656, "source": "mock", "mobile_number": "9800000006"}	\N	2026-08-07 21:14:23.823426+05:30	7
8	2026-08-07 21:14:30.201252+05:30	2026-08-07 21:14:30.201252+05:30	MOCK	865	SUCCESS	{"score": 865, "source": "mock", "mobile_number": "9800000001"}	\N	2026-08-07 21:14:30.201252+05:30	8
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	token_blacklist	blacklistedtoken
7	token_blacklist	outstandingtoken
8	accounts	adminuser
9	credit_score	creditscorerecord
10	bre	businessrule
11	bre	ruleevaluationlog
12	leads	lead
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-08-07 15:48:50.790401+05:30
2	contenttypes	0002_remove_content_type_name	2026-08-07 15:48:50.825633+05:30
3	auth	0001_initial	2026-08-07 15:48:51.037073+05:30
4	auth	0002_alter_permission_name_max_length	2026-08-07 15:48:51.046464+05:30
5	auth	0003_alter_user_email_max_length	2026-08-07 15:48:51.051878+05:30
6	auth	0004_alter_user_username_opts	2026-08-07 15:48:51.064802+05:30
7	auth	0005_alter_user_last_login_null	2026-08-07 15:48:51.069212+05:30
8	auth	0006_require_contenttypes_0002	2026-08-07 15:48:51.069212+05:30
9	auth	0007_alter_validators_add_error_messages	2026-08-07 15:48:51.085721+05:30
10	auth	0008_alter_user_username_max_length	2026-08-07 15:48:51.090482+05:30
11	auth	0009_alter_user_last_name_max_length	2026-08-07 15:48:51.099575+05:30
12	auth	0010_alter_group_name_max_length	2026-08-07 15:48:51.099575+05:30
13	auth	0011_update_proxy_permissions	2026-08-07 15:48:51.117522+05:30
14	auth	0012_alter_user_first_name_max_length	2026-08-07 15:48:51.117522+05:30
15	accounts	0001_initial	2026-08-07 15:48:51.232275+05:30
16	admin	0001_initial	2026-08-07 15:48:51.334905+05:30
17	admin	0002_logentry_remove_auto_add	2026-08-07 15:48:51.359041+05:30
18	admin	0003_logentry_add_action_flag_choices	2026-08-07 15:48:51.392791+05:30
19	leads	0001_initial	2026-08-07 15:48:51.481009+05:30
20	bre	0001_initial	2026-08-07 15:48:51.678753+05:30
21	credit_score	0001_initial	2026-08-07 15:48:51.793688+05:30
22	sessions	0001_initial	2026-08-07 15:48:51.839468+05:30
23	token_blacklist	0001_initial	2026-08-07 15:48:52.032697+05:30
24	token_blacklist	0002_outstandingtoken_jti_hex	2026-08-07 15:48:52.090566+05:30
25	token_blacklist	0003_auto_20171017_2007	2026-08-07 15:48:52.187989+05:30
26	token_blacklist	0004_auto_20171017_2013	2026-08-07 15:48:52.261438+05:30
27	token_blacklist	0005_remove_outstandingtoken_jti	2026-08-07 15:48:52.295432+05:30
28	token_blacklist	0006_auto_20171017_2113	2026-08-07 15:48:52.328045+05:30
29	token_blacklist	0007_auto_20171017_2214	2026-08-07 15:48:52.426343+05:30
30	token_blacklist	0008_migrate_to_bigautofield	2026-08-07 15:48:52.544326+05:30
31	token_blacklist	0010_fix_migrate_to_bigautofield	2026-08-07 15:48:52.639801+05:30
32	token_blacklist	0011_linearizes_history	2026-08-07 15:48:52.645993+05:30
33	token_blacklist	0012_alter_outstandingtoken_user	2026-08-07 15:48:52.688782+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: leads_lead; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.leads_lead (id, created_at, updated_at, full_name, mobile_number, email, date_of_birth, city, pincode, loan_type, employment_type, monthly_income, loan_amount_required, property_value, consent_given, consent_timestamp, credit_score, bre_status) FROM stdin;
1	2026-08-07 15:51:19.372399+05:30	2026-08-07 15:51:19.447417+05:30	Rahul Sharma	9876543210	rahul.sharma@example.com	1990-05-15	Pune	411001	HOME_LOAN	SALARIED	55000.00	2000000.00	3000000.00	t	2026-08-07 15:51:19.372399+05:30	608	NOT_ELIGIBLE
2	2026-08-07 15:52:40.075973+05:30	2026-08-07 15:52:40.113308+05:30	Priya Verma	9123456780	priya.verma@example.com	1988-02-20	Mumbai	400001	LAP	SELF_EMPLOYED	80000.00	1500000.00	3000000.00	t	2026-08-07 15:52:40.074956+05:30	673	NOT_ELIGIBLE
3	2026-08-07 15:53:00.885638+05:30	2026-08-07 15:53:01.201691+05:30	Anita Desai	9000000007	anita.desai@example.com	1985-06-10	Bengaluru	560001	HOME_LOAN	SALARIED	90000.00	2000000.00	3000000.00	t	2026-08-07 15:53:00.885638+05:30	727	ELIGIBLE
4	2026-08-07 15:53:11.07275+05:30	2026-08-07 15:53:11.106596+05:30	Karan Mehta	9876500001	karan.mehta@example.com	1992-03-01	Delhi	110001	HOME_LOAN	SALARIED	60000.00	1000000.00	2000000.00	t	2026-08-07 15:53:11.07275+05:30	327	NOT_ELIGIBLE
5	2026-08-07 16:46:22.996207+05:30	2026-08-07 16:46:23.02726+05:30	Vikram Rao	9988776655	vikram.rao@example.com	1991-07-15	Chennai	600001	HOME_LOAN	SALARIED	70000.00	1000000.00	2500000.00	t	2026-08-07 16:46:22.996207+05:30	725	ELIGIBLE
6	2026-08-07 21:14:10.411487+05:30	2026-08-07 21:14:10.441686+05:30	Sanjay Kulkarni	9800000000	test.applicant@example.com	1992-04-10	Pune	411001	HOME_LOAN	SALARIED	60000.00	1500000.00	3000000.00	t	2026-08-07 21:14:10.410891+05:30	831	ELIGIBLE
7	2026-08-07 21:14:23.810064+05:30	2026-08-07 21:14:23.852615+05:30	Rejected Case	9800000006	test.applicant@example.com	1992-04-10	Pune	411001	HOME_LOAN	SALARIED	60000.00	1500000.00	3000000.00	t	2026-08-07 21:14:23.810064+05:30	656	NOT_ELIGIBLE
8	2026-08-07 21:14:30.188725+05:30	2026-08-07 21:14:30.227795+05:30	Mobile View Test	9800000001	test.applicant@example.com	1992-04-10	Pune	411001	HOME_LOAN	SALARIED	60000.00	1500000.00	3000000.00	t	2026-08-07 21:14:30.188725+05:30	865	ELIGIBLE
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcwMjg0NCwiaWF0IjoxNzg2MDk4MDQ0LCJqdGkiOiJlY2Y5M2ExMzA5Zjc0MDczOWM1NGEzN2Q3YjBiYTc4OSIsInVzZXJfaWQiOjF9.EGY7f7ts3zvCwcy18XVyRC7OD00FCTm4-yfjzXPodxk	2026-08-07 15:50:44.91744+05:30	2026-08-14 15:50:44+05:30	1	ecf93a1309f740739c54a37d7b0ba789
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcwNTcxNSwiaWF0IjoxNzg2MTAwOTE1LCJqdGkiOiI5YTdiZDc3YTczNjk0ZGU4ODFkOWNhZjU5MzE3MDZlOCIsInVzZXJfaWQiOjF9.GzIqTZgo9iFpHWuIwgmPgQLdG-6yVSJheMAkzv_zSXk	2026-08-07 16:38:35.030924+05:30	2026-08-14 16:38:35+05:30	1	9a7bd77a73694de881d9caf5931706e8
3	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcwNTg2NiwiaWF0IjoxNzg2MTAxMDY2LCJqdGkiOiIyZWZhY2IyMTY5MTY0ZmFjOTFlMWZjODYyNjFjNDY4MiIsInVzZXJfaWQiOjF9.KAXnl3gcbC5vwr73sONqyndvuArW8HPRDqsC3mRujUM	2026-08-07 16:41:06.954445+05:30	2026-08-14 16:41:06+05:30	1	2efacb2169164fac91e1fc86261c4682
4	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcwNjA2MCwiaWF0IjoxNzg2MTAxMjYwLCJqdGkiOiIzMWYzYWY3NWZmMjA0MDExYWNkNjNmMTQ4Y2ZmMWI5YiIsInVzZXJfaWQiOjF9.EQl4tYiRp90cSqmUqJyJKcwBtcZtNZve_isLyYPTCK8	2026-08-07 16:44:20.885421+05:30	2026-08-14 16:44:20+05:30	1	31f3af75ff204011acd63f148cff1b9b
5	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcwNjE4NiwiaWF0IjoxNzg2MTAxMzg2LCJqdGkiOiJiZjJkN2Q4NzBlYWQ0NWEzYTI3YzU3NDFlZDk0M2Q4ZiIsInVzZXJfaWQiOjF9.-BLCvAW1K0IztAENxxPbhLVuXasak54k7POx68Xda9s	2026-08-07 16:46:26.370351+05:30	2026-08-14 16:46:26+05:30	1	bf2d7d870ead45a3a27c5741ed943d8f
6	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcyMDE5NiwiaWF0IjoxNzg2MTE1Mzk2LCJqdGkiOiIwYTM2ZjhjNjQ2YjI0ZDNjYWQyODdhMTIyYWQ3ZWVjYiIsInVzZXJfaWQiOjF9.CQz4ulhQ5a6V0RT85uRCdHHZgYrxutPYpJApJjV2weM	2026-08-07 20:39:56.742092+05:30	2026-08-14 20:39:56+05:30	1	0a36f8c646b24d3cad287a122ad7eecb
7	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcyMDI0OCwiaWF0IjoxNzg2MTE1NDQ4LCJqdGkiOiI0MDkxYjlkMDYwMWI0NWIzOWQxYTQ5YTE1MWI4YzQyMiIsInVzZXJfaWQiOjF9.KzqK-p1gzf6m83NjRQSSQT4mZcLgmgg-aaYZHtbvNq4	2026-08-07 20:40:48.970367+05:30	2026-08-14 20:40:48+05:30	1	4091b9d0601b45b39d1a49a151b8c422
8	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcyMDI3OCwiaWF0IjoxNzg2MTE1NDc4LCJqdGkiOiJiNzcyZWY1NzBkZWM0ODgyYmQ2Njc1MDBlMWJkNzllZCIsInVzZXJfaWQiOjF9.RzKCMlmGwiEleMYrudCXfswun6pLrcHq8rM6sfHegeA	2026-08-07 20:41:18.770697+05:30	2026-08-14 20:41:18+05:30	1	b772ef570dec4882bd667500e1bd79ed
9	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcyMDM4NSwiaWF0IjoxNzg2MTE1NTg1LCJqdGkiOiIxMDcyZGYzNzkwNTc0YTg5ODRmMTQ3MDFiYTg4NTEwMCIsInVzZXJfaWQiOjF9.Yf7xMezdPnuKnfZfKkK7EsUQau5TJWuZlH-dXRF9-ec	2026-08-07 20:43:05.54216+05:30	2026-08-14 20:43:05+05:30	1	1072df3790574a8984f14701ba885100
10	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcyMTk4NCwiaWF0IjoxNzg2MTE3MTg0LCJqdGkiOiI2MTA5MzQ5NGQyMWM0NjQzODgwNGEyM2Y5NTI1NTNiNyIsInVzZXJfaWQiOjF9.01Q7rwF6dZinzRIuYaLYJVvqOG9BfYnZwXQdaRBXYa8	2026-08-07 21:09:44.045322+05:30	2026-08-14 21:09:44+05:30	1	61093494d21c46438804a23f952553b7
11	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcyMzQxMCwiaWF0IjoxNzg2MTE4NjEwLCJqdGkiOiI0NGY2ZDBhZjIzNDg0YjE0ODhhYjYwYjk4MmJlZjkyMCIsInVzZXJfaWQiOjF9.cWu91s38kxmdTfPrkzujjcxW46EmSt7JESIh0VSBjoc	2026-08-07 21:33:30.485635+05:30	2026-08-14 21:33:30+05:30	1	44f6d0af23484b1488ab60b982bef920
12	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcyMzUwMSwiaWF0IjoxNzg2MTE4NzAxLCJqdGkiOiI4YjNiYjYwYmVmN2M0MTU1YjAzYjZlNzE0MmIwN2VjYSIsInVzZXJfaWQiOjF9.3ACXxvFAXS8bU8WaJbLnis6Ocwif8c4FUqipze-5Blo	2026-08-07 21:35:01.410414+05:30	2026-08-14 21:35:01+05:30	1	8b3bb60bef7c4155b03b6e7142b07eca
13	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcyNDQ5MSwiaWF0IjoxNzg2MTE5NjkxLCJqdGkiOiI5OWMzODM1ZmJiMzM0MjQ4ODUyZWZhMmJjYzk4MTIzOCIsInVzZXJfaWQiOjF9.WqnQtfITmkCLecpb9ObiyZaYy72D7FoZeNllEKoquQQ	2026-08-07 21:51:31.737936+05:30	2026-08-14 21:51:31+05:30	1	99c3835fbb334248852efa2bcc981238
14	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcyNDU5MywiaWF0IjoxNzg2MTE5NzkzLCJqdGkiOiIyZTJmNGMzNTBjMzg0OGU0OTZhY2I5YWE3MGM1NTNlNiIsInVzZXJfaWQiOjF9.V2GI_4eZ9jgyjIVp15_geB8YuScGRAs5dcE_5zxv_To	2026-08-07 21:53:13.170972+05:30	2026-08-14 21:53:13+05:30	1	2e2f4c350c3848e496acb9aa70c553e6
15	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcyNDY0MCwiaWF0IjoxNzg2MTE5ODQwLCJqdGkiOiJiYzE5YzZjM2Q5OTM0Yjg1ODMyNTIyYjhjZmViZWQ1NyIsInVzZXJfaWQiOjF9.AjI7qd8seH82O0Czzu41yUXfIOAC5Yky0wUfGILQ_mU	2026-08-07 21:54:00.872585+05:30	2026-08-14 21:54:00+05:30	1	bc19c6c3d9934b85832522b8cfebed57
16	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcyNzQ2MSwiaWF0IjoxNzg2MTIyNjYxLCJqdGkiOiI0NzVlZDZlNDQyMDc0NzI0YWY1MmI2OTFmOTM4NDJjYSIsInVzZXJfaWQiOjF9.Y3KU9B5q5mzjRIFLAndzHsI2lFjQyws_59oBRxRK_A4	2026-08-07 22:41:01.562971+05:30	2026-08-14 22:41:01+05:30	1	475ed6e442074724af52b691f93842ca
17	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcyNzQ5NywiaWF0IjoxNzg2MTIyNjk3LCJqdGkiOiI3YmI2NGM4YWViZWI0YWVjYjAxNGI0MDdkYzU5Zjc2NCIsInVzZXJfaWQiOjF9.5YAhJWCYVR62Z8X60yKJAMSOOhoUS1HjGOZAuLr7ZWI	2026-08-07 22:41:37.163535+05:30	2026-08-14 22:41:37+05:30	1	7bb64c8aebeb4aecb014b407dc59f764
18	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcyNzUzMiwiaWF0IjoxNzg2MTIyNzMyLCJqdGkiOiI5ZDIyZGVhNWY3NWY0MDk2YmY2YzA3ZmVkM2M4ZDQwMyIsInVzZXJfaWQiOjF9.I2zRa5MFAiLuEhbTmtEAzoE7SCQYJDTBeJUtD-Flc5o	2026-08-07 22:42:12.090163+05:30	2026-08-14 22:42:12+05:30	1	9d22dea5f75f4096bf6c07fed3c8d403
19	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcyNzcwMiwiaWF0IjoxNzg2MTIyOTAyLCJqdGkiOiIxOTZkYWQ2MTYxNzg0OGRiYTE2NzI4MDAxNjgwNGYwYyIsInVzZXJfaWQiOjF9.vyYU7_xPHXTvsh9OtYACFwgX8tI2VHg3KxnMBc-A7eE	2026-08-07 22:45:02.511648+05:30	2026-08-14 22:45:02+05:30	1	196dad61617848dba167280016804f0c
20	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcyNzkzNiwiaWF0IjoxNzg2MTIzMTM2LCJqdGkiOiIzYTNmNGNhYzFmYzQ0N2I1YTg2MDBiZWU4OTllY2RkZiIsInVzZXJfaWQiOjF9.zAPhuFo6SJzQMykk7k1pU7l6EgfyHOul3_ReZ_rL3Y0	2026-08-07 22:48:56.273984+05:30	2026-08-14 22:48:56+05:30	1	3a3f4cac1fc447b5a8600bee899ecddf
21	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NjcyODg1OSwiaWF0IjoxNzg2MTI0MDU5LCJqdGkiOiIwZThkMjFkNmM2ZDc0Nzg3OTViOTMxMTllZTUxNjA0YyIsInVzZXJfaWQiOjF9.6PX0pE1oa6-506Y1qNr_KqEl9Tgkba3ugm18imo_NAw	2026-08-07 23:04:19.086155+05:30	2026-08-14 23:04:19+05:30	1	0e8d21d6c6d7478795b93119ee51604c
\.


--
-- Name: accounts_adminuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_adminuser_groups_id_seq', 1, false);


--
-- Name: accounts_adminuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_adminuser_id_seq', 1, true);


--
-- Name: accounts_adminuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_adminuser_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 48, true);


--
-- Name: bre_businessrule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.bre_businessrule_id_seq', 6, true);


--
-- Name: bre_ruleevaluationlog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.bre_ruleevaluationlog_id_seq', 40, true);


--
-- Name: credit_score_creditscorerecord_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.credit_score_creditscorerecord_id_seq', 8, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 12, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 33, true);


--
-- Name: leads_lead_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.leads_lead_id_seq', 8, true);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 1, false);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 21, true);


--
-- Name: accounts_adminuser accounts_adminuser_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_adminuser
    ADD CONSTRAINT accounts_adminuser_email_key UNIQUE (email);


--
-- Name: accounts_adminuser_groups accounts_adminuser_groups_adminuser_id_group_id_9ada8b9a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_adminuser_groups
    ADD CONSTRAINT accounts_adminuser_groups_adminuser_id_group_id_9ada8b9a_uniq UNIQUE (adminuser_id, group_id);


--
-- Name: accounts_adminuser_groups accounts_adminuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_adminuser_groups
    ADD CONSTRAINT accounts_adminuser_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_adminuser accounts_adminuser_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_adminuser
    ADD CONSTRAINT accounts_adminuser_pkey PRIMARY KEY (id);


--
-- Name: accounts_adminuser_user_permissions accounts_adminuser_user__adminuser_id_permission__0e9ac9f4_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_adminuser_user_permissions
    ADD CONSTRAINT accounts_adminuser_user__adminuser_id_permission__0e9ac9f4_uniq UNIQUE (adminuser_id, permission_id);


--
-- Name: accounts_adminuser_user_permissions accounts_adminuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_adminuser_user_permissions
    ADD CONSTRAINT accounts_adminuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_adminuser accounts_adminuser_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_adminuser
    ADD CONSTRAINT accounts_adminuser_username_key UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: bre_businessrule bre_businessrule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bre_businessrule
    ADD CONSTRAINT bre_businessrule_pkey PRIMARY KEY (id);


--
-- Name: bre_ruleevaluationlog bre_ruleevaluationlog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bre_ruleevaluationlog
    ADD CONSTRAINT bre_ruleevaluationlog_pkey PRIMARY KEY (id);


--
-- Name: credit_score_creditscorerecord credit_score_creditscorerecord_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_score_creditscorerecord
    ADD CONSTRAINT credit_score_creditscorerecord_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: leads_lead leads_lead_mobile_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leads_lead
    ADD CONSTRAINT leads_lead_mobile_number_key UNIQUE (mobile_number);


--
-- Name: leads_lead leads_lead_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leads_lead
    ADD CONSTRAINT leads_lead_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: accounts_adminuser_email_5110578e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_adminuser_email_5110578e_like ON public.accounts_adminuser USING btree (email varchar_pattern_ops);


--
-- Name: accounts_adminuser_groups_adminuser_id_d27820d1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_adminuser_groups_adminuser_id_d27820d1 ON public.accounts_adminuser_groups USING btree (adminuser_id);


--
-- Name: accounts_adminuser_groups_group_id_fa364085; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_adminuser_groups_group_id_fa364085 ON public.accounts_adminuser_groups USING btree (group_id);


--
-- Name: accounts_adminuser_user_permissions_adminuser_id_5ee267b3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_adminuser_user_permissions_adminuser_id_5ee267b3 ON public.accounts_adminuser_user_permissions USING btree (adminuser_id);


--
-- Name: accounts_adminuser_user_permissions_permission_id_c848505f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_adminuser_user_permissions_permission_id_c848505f ON public.accounts_adminuser_user_permissions USING btree (permission_id);


--
-- Name: accounts_adminuser_username_4d9b2ca6_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_adminuser_username_4d9b2ca6_like ON public.accounts_adminuser USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: bre_businessrule_created_by_id_4f299156; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bre_businessrule_created_by_id_4f299156 ON public.bre_businessrule USING btree (created_by_id);


--
-- Name: bre_ruleevaluationlog_lead_id_6756367c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bre_ruleevaluationlog_lead_id_6756367c ON public.bre_ruleevaluationlog USING btree (lead_id);


--
-- Name: bre_ruleevaluationlog_rule_id_9bc23a3c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bre_ruleevaluationlog_rule_id_9bc23a3c ON public.bre_ruleevaluationlog USING btree (rule_id);


--
-- Name: credit_score_creditscorerecord_lead_id_27c9c6bc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX credit_score_creditscorerecord_lead_id_27c9c6bc ON public.credit_score_creditscorerecord USING btree (lead_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: leads_lead_bre_sta_28c586_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leads_lead_bre_sta_28c586_idx ON public.leads_lead USING btree (bre_status);


--
-- Name: leads_lead_loan_ty_914061_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leads_lead_loan_ty_914061_idx ON public.leads_lead USING btree (loan_type);


--
-- Name: leads_lead_mobile_number_3998bc4b_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leads_lead_mobile_number_3998bc4b_like ON public.leads_lead USING btree (mobile_number varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: accounts_adminuser_groups accounts_adminuser_g_adminuser_id_d27820d1_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_adminuser_groups
    ADD CONSTRAINT accounts_adminuser_g_adminuser_id_d27820d1_fk_accounts_ FOREIGN KEY (adminuser_id) REFERENCES public.accounts_adminuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_adminuser_groups accounts_adminuser_groups_group_id_fa364085_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_adminuser_groups
    ADD CONSTRAINT accounts_adminuser_groups_group_id_fa364085_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_adminuser_user_permissions accounts_adminuser_u_adminuser_id_5ee267b3_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_adminuser_user_permissions
    ADD CONSTRAINT accounts_adminuser_u_adminuser_id_5ee267b3_fk_accounts_ FOREIGN KEY (adminuser_id) REFERENCES public.accounts_adminuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_adminuser_user_permissions accounts_adminuser_u_permission_id_c848505f_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_adminuser_user_permissions
    ADD CONSTRAINT accounts_adminuser_u_permission_id_c848505f_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bre_businessrule bre_businessrule_created_by_id_4f299156_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bre_businessrule
    ADD CONSTRAINT bre_businessrule_created_by_id_4f299156_fk_accounts_ FOREIGN KEY (created_by_id) REFERENCES public.accounts_adminuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bre_ruleevaluationlog bre_ruleevaluationlog_lead_id_6756367c_fk_leads_lead_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bre_ruleevaluationlog
    ADD CONSTRAINT bre_ruleevaluationlog_lead_id_6756367c_fk_leads_lead_id FOREIGN KEY (lead_id) REFERENCES public.leads_lead(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bre_ruleevaluationlog bre_ruleevaluationlog_rule_id_9bc23a3c_fk_bre_businessrule_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bre_ruleevaluationlog
    ADD CONSTRAINT bre_ruleevaluationlog_rule_id_9bc23a3c_fk_bre_businessrule_id FOREIGN KEY (rule_id) REFERENCES public.bre_businessrule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: credit_score_creditscorerecord credit_score_credits_lead_id_27c9c6bc_fk_leads_lea; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_score_creditscorerecord
    ADD CONSTRAINT credit_score_credits_lead_id_27c9c6bc_fk_leads_lea FOREIGN KEY (lead_id) REFERENCES public.leads_lead(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_adminuser_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_adminuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_adminuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_adminuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict fMD8Y1oOqGUyX5XlQy17Mm0VGCe68eyOguFJDZu1kT6OgvuKXwOV0M56W0aPr4m

